project_id = "tlawfdsvtbcmagkieaui"

[functions.create-coordinator-account]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-feedback-notification]
verify_jwt = false
[auth]
jwt_expiry = 604800
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
