project_id = "tlawfdsvtbcmagkieaui"

[functions.create-coordinator-account]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-feedback-notification]
verify_jwt = false